pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('Init') {
            steps {
                sh """
                   cd 01-vpc
                   terraform init -reconfigure
                """
            }
        }

        stage('Plan') {
            steps {
                sh """
                   cd 01-vpc
                   terraform plan
                """
            }
        }

        stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again'
        }
        failure {
            echo 'This will run when pipeline is failed, used generally to send some alerts'
        }
        success {
            echo 'I will say Hello again when pipeline is successful'
        }
    }
}

